---
- hosts: all
  become: yes
  tasks:
  - name: make sure data node folder exists
    file:
      path: /home/ubuntu/hadoop_store/hdfs/datanode2
      state: directory
      mode: 0775
      recurse: yes
...
