---
- hosts: all
  become: yes
  tasks:
    # Add packages
    - name: Add software-properties-common to support the add-apt-library
      apt:
        pkg: software-properties-common
        state: installed
        update_cache: yes
    - name: Add python-software-properties to support the JAVA library
      apt:
        pkg: python-software-properties
        state: installed
        update_cache: yes
    - name: Add java repository
      apt_repository:
        repo: ppa:openjdk-r/ppa
        update_cache: yes
    - name: Make sure Java is installed
      apt:
        pkg: openjdk-8-jdk
        state: installed
        update_cache: yes
    - name: Make sure SSH is installed
      apt:
        pkg: ssh
        state: installed
        update_cache: yes
    - name: Make sure git is installed
      apt:
        pkg: git
        state: installed
        update_cache: yes
    - name: make sure we have the latest vagrant hadoop repo
      git:
        repo: 'https://github.com/ajferrario/vagrant-hadoop.git'
        dest: /home/ubuntu/vagrant-hadoop
    - name: add hadoop user group
      group:
        name: hadoop
    - name: Allow 'hadoop' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%hadoop'
        line: '%hadoop ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
    - name: Add hduser to hadoop group
      user:
        name: hduser
        groups: hadoop
        append: yes
        state: present
        createhome: yes
        generate_ssh_key: yes
    - name: create hduser
      user:
        name: hduser
        group: hadoop
        generate_ssh_key: yes
    - name: Download and unpack Hadoop
      unarchive:
        src: http://www.trieuvan.com/apache/hadoop/common/hadoop-2.8.2/hadoop-2.8.2.tar.gz
        dest: /usr/local
        remote_src: yes
    - name: softlink to hadoop
      command: ln -s /usr/local/hadoop-2.8.2 /usr/local/hadoop
    - name: set owner of hadoop folder to hduser
      command: chown -R hduser:hadoop /usr/local/hadoop
    - name: set owner of real hadoop folder to hduser
      command: chown -R hduser:hadoop /usr/local/hadoop-2.8.2
    - name: create hdfs directory
      file:
        path: /hdfs_storage/data
        state: directory
        owner: hduser
        recurse: yes
    - name: set JAVA HOME in bashrc
      lineinfile:
        path: ~/.bashrc
        line: 'export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64'
    - name: set HADOOP_HOME in bashrc
      lineinfile:
        path: ~/.bashrc
        line: 'export HADOOP_HOME=/usr/local/hadoop'
    - name: add HADOOP_HOME to PATH in bashrc
      lineinfile:
        path: ~/.bashrc
        line: 'export PATH=$PATH:$HADOOP_HOME/bin:$HADOOP_HOME/sbin'
    #- name: update our bashrc
    #  command: source ~/.bashrc
    - name: update hadoop-env.sh
      command: mv -f /home/ubuntu/vagrant-hadoop/config/hadoop-env.sh /usr/local/hadoop/etc/hadoop/hadoop-env.sh
    - name: update core-site.xml
      command: mv -f /home/ubuntu/vagrant-hadoop/config/core-site.xml /usr/local/hadoop/etc/hadoop/core-site.xml
    - name: update mapred-site.xml
      command: mv -f /home/ubuntu/vagrant-hadoop/config/mapred-site.xml /usr/local/hadoop/etc/hadoop/mapred-site.xml
    - name: update yarn-site.xml
      command: mv -f /home/ubuntu/vagrant-hadoop/config/yarn-site.xml /usr/local/hadoop/etc/hadoop/yarn-site.xml
    - name: update hosts
      command: mv -f /home/ubuntu/vagrant-hadoop/config/hosts /etc/hosts
...
