---
- hosts: all
  become: yes
  tasks:
      - name: update hdfs-site.xml
        command: mv -f /home/ubuntu/vagrant-hadoop/config/secondary/hdfs-site.xml /usr/local/hadoop/etc/hadoop/hdfs-site.xml
      - name: create fsimage directory
        file:
          path: /hdfs_storage/snnfsi
          state: directory
          owner: hduser
          recurse: yes
      - name: create fs edits directory
        file:
          path: /hdfs_storage/snnedits
          state: directory
          owner: hduser
          recurse: yes
...
